export const API_URL = 'http://localhost:8080/';

export const PERMISSIONS_CHECK_REQUEST = 'PERMISSIONS_CHECK_REQUEST';
export const PERMISSIONS_CHECK_SUCCESS = 'PERMISSIONS_CHECK_SUCCESS';
export const PERMISSIONS_CHECK_ERROR = 'PERMISSIONS_CHECK_ERROR';

export const PRODUCT_ADD_REQUEST = 'PRODUCT_ADD_REQUEST';
export const PRODUCT_ADD_SUCCESS = 'PRODUCT_ADD_SUCCESS';
export const PRODUCT_ADD_ERROR = 'PRODUCT_ADD_ERROR';

export const PRODUCT_GET_ALL_REQUEST = 'PRODUCT_GET_ALL_REQUEST';
export const PRODUCT_GET_ALL_SUCCESS = 'PRODUCT_GET_ALL_SUCCESS';
export const PRODUCT_GET_ALL_ERROR = 'PRODUCT_GET_ALL_ERROR';